import = ["~/.config/alacritty/themes/campbell.toml"]

[window]
dimensions = {columns=85, lines=42}
padding = {x=10, y=20}
opacity = 0.95
blur = true

[font]
normal = {family = "JetbrainsMono Nerd Font", style = "Regular"}
offset = {x=0, y=1}
glyph_offset = {x=0, y=1}

[cursor]
style = {shape="Block", blinking="On" }
blink_timeout = 30

